# Generated by Django 4.0.5 on 2022-06-14 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_my'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my',
            name='email',
        ),
    ]
