# Generated by Django 4.0.5 on 2022-06-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_my_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='down',
            old_name='text',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='my',
            name='img',
        ),
        migrations.AddField(
            model_name='down',
            name='height',
            field=models.IntegerField(default=2000),
        ),
    ]
